module.exports = [ { id: 10012122,
    id_str: '10012122',
    name: 'BBC Mundo',
    screen_name: 'bbcmundo',
    location: 'Londres, Inglaterra.',
    description: 'Twitter oficial de BBC Mundo. Aquí encuentran una selección de lo mejor de nuestro contenido y los invitamos a una conversación global. ¿Se animan?',
    url: 'http://t.co/7iztWgfVKa',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 2373713,
    friends_count: 363,
    listed_count: 17903,
    created_at: 'Tue Nov 06 21:50:06 +0000 2007',
    favourites_count: 830,
    utc_offset: 3600,
    time_zone: 'London',
    geo_enabled: true,
    verified: true,
    statuses_count: 190101,
    lang: 'en',
    status:
     { created_at: 'Fri Jul 28 12:40:42 +0000 2017',
       id: 890914912083562500,
       id_str: '890914912083562496',
       text: 'Quina, el casi extinto árbol medicinal del escudo de Perú que ni los patriotas conocen e inspiró el gin tonic https://t.co/wQZOyacaWr',
       truncated: false,
       entities: [Object],
       source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 30,
       favorite_count: 35,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'es' },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'FFFFFF',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/80111333/twitter_final_bg.jpg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/80111333/twitter_final_bg.jpg',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/2364324949/4gp59x1puhpspi60jgzn_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/2364324949/4gp59x1puhpspi60jgzn_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/10012122/1492017825',
    profile_link_color: '003366',
    profile_sidebar_border_color: 'C2C2C2',
    profile_sidebar_fill_color: 'E8E8E8',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: true,
    live_following: false,
    follow_request_sent: false,
    notifications: false,
    muting: false,
    blocking: false,
    blocked_by: false,
    translator_type: 'none' },
  { id: 18191307,
    id_str: '18191307',
    name: 'Хабрахабр',
    screen_name: 'habrahabr',
    location: 'Moscow',
    description: 'Сообщество IT-специалистов. Just do IT.',
    url: 'http://t.co/AAzQTp7cWw',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 411031,
    friends_count: 52,
    listed_count: 3199,
    created_at: 'Wed Dec 17 15:41:34 +0000 2008',
    favourites_count: 13,
    utc_offset: 10800,
    time_zone: 'Volgograd',
    geo_enabled: false,
    verified: true,
    statuses_count: 88842,
    lang: 'ru',
    status:
     { created_at: 'Fri Jul 28 12:36:12 +0000 2017',
       id: 890913779252416500,
       id_str: '890913779252416512',
       text: 'Как «Актив» организовал «электронную переговорку» https://t.co/n7SE9njfWV https://t.co/LZQ5x2hkEc',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       source: '<a href="http://amplifr.com" rel="nofollow">Amplifr</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 1,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'ru' },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/583482649924218881/HbQGtx57_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/583482649924218881/HbQGtx57_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/18191307/1480563372',
    profile_link_color: '93B4CA',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: true,
    live_following: false,
    follow_request_sent: false,
    notifications: false,
    muting: false,
    blocking: false,
    blocked_by: false,
    translator_type: 'none' },
  { id: 459275531,
    id_str: '459275531',
    name: 'JavaScript Daily',
    screen_name: 'JavaScriptDaily',
    location: '',
    description: 'Daily JavaScript / JS community news, links and events. Go to @reactdaily for React news.',
    url: 'http://t.co/yTZ4fsOxGj',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 271241,
    friends_count: 160,
    listed_count: 5557,
    created_at: 'Mon Jan 09 13:43:05 +0000 2012',
    favourites_count: 608,
    utc_offset: -25200,
    time_zone: 'Pacific Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 8466,
    lang: 'en',
    status:
     { created_at: 'Fri Jul 28 11:48:04 +0000 2017',
       id: 890901668266639400,
       id_str: '890901668266639362',
       text: 'Node Emerging as the Universal Development Framework for a Diversity of Apps: https://t.co/yw9RXKfu8g',
       truncated: false,
       entities: [Object],
       source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 20,
       favorite_count: 43,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '51CBBF',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/558331836/jsbg.png',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/558331836/jsbg.png',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/877477206418653184/W63ZlNa1_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/877477206418653184/W63ZlNa1_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/459275531/1458214369',
    profile_link_color: 'D4BB00',
    profile_sidebar_border_color: 'F0EDDA',
    profile_sidebar_fill_color: 'FDFFF0',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: true,
    live_following: false,
    follow_request_sent: false,
    notifications: false,
    muting: false,
    blocking: false,
    blocked_by: false,
    translator_type: 'none' },
  { id: 6433472,
    id_str: '6433472',
    name: 'CBC News',
    screen_name: 'CBCNews',
    location: 'Canada',
    description: 'Canadian breaking news and analysis from CBCNews.ca, TV and radio.',
    url: 'http://t.co/ZLZObOnET1',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 2384766,
    friends_count: 2703,
    listed_count: 13625,
    created_at: 'Wed May 30 05:20:39 +0000 2007',
    favourites_count: 5622,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: true,
    verified: true,
    statuses_count: 178860,
    lang: 'en',
    status:
     { created_at: 'Fri Jul 28 12:45:05 +0000 2017',
       id: 890916016204787700,
       id_str: '890916016204787712',
       text: 'RT @CBCAlerts: Political turmoil in Pakistan as country\'s top court forces PM Nawaz Sharif from office in wake of corruption probe. https:/…',
       truncated: false,
       entities: [Object],
       source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 9,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/167724092/cbcnews_twitter_pg-yellow.JPG',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/167724092/cbcnews_twitter_pg-yellow.JPG',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/886935212722184192/Z5FBfGsp_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/886935212722184192/Z5FBfGsp_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/6433472/1400096610',
    profile_link_color: 'FF0000',
    profile_sidebar_border_color: 'F2E195',
    profile_sidebar_fill_color: 'FFF7CC',
    profile_text_color: '0C3E53',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: true,
    live_following: false,
    follow_request_sent: false,
    notifications: false,
    muting: false,
    blocking: false,
    blocked_by: false,
    translator_type: 'none' },
  { id: 14260960,
    id_str: '14260960',
    name: 'Justin Trudeau',
    screen_name: 'JustinTrudeau',
    location: 'Papineau',
    description: 'Account run by the 23rd Prime Minister of Canada and staff… Compte géré par le 23e premier ministre du Canada et personnel.',
    url: 'https://t.co/wbkAcy1QE7',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 3466492,
    friends_count: 961,
    listed_count: 11067,
    created_at: 'Sun Mar 30 21:04:14 +0000 2008',
    favourites_count: 64,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: true,
    verified: true,
    statuses_count: 15208,
    lang: 'en',
    status:
     { created_at: 'Thu Jul 27 22:05:32 +0000 2017',
       id: 890694669889417200,
       id_str: '890694669889417216',
       text: 'Busy afternoon back in Ottawa today – heading West tomorrow. https://t.co/1UvjOdBvAI',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 213,
       favorite_count: 2158,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'DBDCDD',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/538085032842113025/cK69w4mC.png',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/538085032842113025/cK69w4mC.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/816404989392211968/Wv_8ZDrX_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/816404989392211968/Wv_8ZDrX_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/14260960/1499699762',
    profile_link_color: 'B50000',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'B80B0B',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: true,
    live_following: false,
    follow_request_sent: false,
    notifications: false,
    muting: false,
    blocking: false,
    blocked_by: false,
    translator_type: 'none' } ];